remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: 'League of Legends: The Impact of Monster Objectives on Wins'
description: UCSD DSC80 Project Analyzing the Effect of Monster Objectives on Wins, by Samuel Cho